# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\form\serialmonitor.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.sendGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendGroupBox.sizePolicy().hasHeightForWidth())
        self.sendGroupBox.setSizePolicy(sizePolicy)
        self.sendGroupBox.setObjectName("sendGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.sendGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sendLineEdit = QtWidgets.QLineEdit(self.sendGroupBox)
        self.sendLineEdit.setObjectName("sendLineEdit")
        self.horizontalLayout.addWidget(self.sendLineEdit)
        self.sendPushButton = QtWidgets.QPushButton(self.sendGroupBox)
        self.sendPushButton.setObjectName("sendPushButton")
        self.horizontalLayout.addWidget(self.sendPushButton)
        self.gridLayout.addWidget(self.sendGroupBox, 2, 0, 1, 1)
        self.monitorGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monitorGroupBox.sizePolicy().hasHeightForWidth())
        self.monitorGroupBox.setSizePolicy(sizePolicy)
        self.monitorGroupBox.setObjectName("monitorGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.monitorGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.monitorGroupBox)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.monitorGroupBox, 0, 0, 2, 1)
        self.settingsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsGroupBox.sizePolicy().hasHeightForWidth())
        self.settingsGroupBox.setSizePolicy(sizePolicy)
        self.settingsGroupBox.setObjectName("settingsGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.settingsGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.serialPortLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.serialPortLabel.setObjectName("serialPortLabel")
        self.gridLayout_3.addWidget(self.serialPortLabel, 0, 0, 1, 1)
        self.serialPortComboBox = QtWidgets.QComboBox(self.settingsGroupBox)
        self.serialPortComboBox.setObjectName("serialPortComboBox")
        self.gridLayout_3.addWidget(self.serialPortComboBox, 0, 1, 1, 1)
        self.baudRateLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.baudRateLabel.setObjectName("baudRateLabel")
        self.gridLayout_3.addWidget(self.baudRateLabel, 1, 0, 1, 1)
        self.baudRateComboBox = QtWidgets.QComboBox(self.settingsGroupBox)
        self.baudRateComboBox.setObjectName("baudRateComboBox")
        self.gridLayout_3.addWidget(self.baudRateComboBox, 1, 1, 1, 1)
        self.dataBitLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.dataBitLabel.setObjectName("dataBitLabel")
        self.gridLayout_3.addWidget(self.dataBitLabel, 2, 0, 1, 1)
        self.dataBitComboBox = QtWidgets.QComboBox(self.settingsGroupBox)
        self.dataBitComboBox.setObjectName("dataBitComboBox")
        self.gridLayout_3.addWidget(self.dataBitComboBox, 2, 1, 1, 1)
        self.parityLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.parityLabel.setObjectName("parityLabel")
        self.gridLayout_3.addWidget(self.parityLabel, 3, 0, 1, 1)
        self.parityComboBox = QtWidgets.QComboBox(self.settingsGroupBox)
        self.parityComboBox.setObjectName("parityComboBox")
        self.gridLayout_3.addWidget(self.parityComboBox, 3, 1, 1, 1)
        self.stopBitLabel = QtWidgets.QLabel(self.settingsGroupBox)
        self.stopBitLabel.setObjectName("stopBitLabel")
        self.gridLayout_3.addWidget(self.stopBitLabel, 4, 0, 1, 1)
        self.stopBitComboBox = QtWidgets.QComboBox(self.settingsGroupBox)
        self.stopBitComboBox.setObjectName("stopBitComboBox")
        self.gridLayout_3.addWidget(self.stopBitComboBox, 4, 1, 1, 1)
        self.applyPushButton = QtWidgets.QPushButton(self.settingsGroupBox)
        self.applyPushButton.setObjectName("applyPushButton")
        self.gridLayout_3.addWidget(self.applyPushButton, 5, 1, 1, 1)
        self.gridLayout.addWidget(self.settingsGroupBox, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        MainWindow.setMenuBar(self.menubar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFIle.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFIle.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SerialMonitor"))
        self.sendGroupBox.setTitle(_translate("MainWindow", "Send Box"))
        self.sendPushButton.setText(_translate("MainWindow", "Send"))
        self.monitorGroupBox.setTitle(_translate("MainWindow", "Monitor"))
        self.settingsGroupBox.setTitle(_translate("MainWindow", "Settings"))
        self.serialPortLabel.setText(_translate("MainWindow", "Serial Port"))
        self.baudRateLabel.setText(_translate("MainWindow", "Baud Rate"))
        self.dataBitLabel.setText(_translate("MainWindow", "Data Bit"))
        self.parityLabel.setText(_translate("MainWindow", "Parity Bit"))
        self.stopBitLabel.setText(_translate("MainWindow", "Stop Bit"))
        self.applyPushButton.setText(_translate("MainWindow", "Apply"))
        self.menuFIle.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
